services:

  postgres-auth:
    image: postgres:latest
    container_name: postgres-auth
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_AUTH_USERNAME} -d auth_db" ]
      interval: 10s
      timeout: 8s
      retries: 5
    environment:
      POSTGRES_USER: ${DB_AUTH_USERNAME}
      POSTGRES_PASSWORD: ${DB_AUTH_PASSWORD}
      POSTGRES_DB: auth_db
      PGDATA: /data/postgres
    ports:
      - '5431:5432'
    volumes:
      - C:\rade-share-x-data\auth:/data/postgres
    networks:
      - ridesharex-net
    restart: unless-stopped

  configuration-server:
    build: config-server
    image: config-server:1.0.0
    container_name: config-server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 8s
      retries: 5
    ports:
      - "8888:8080"
    environment:
      GIT_USER: ${GIT_USER}
      CONFIG_REPOSITORY: ${CONFIG_REPOSITORY}
      GIT_PASSWORD: ${GIT_PASSWORD}
    restart: on-failure:5
    networks:
      - ridesharex-net
    mem_limit: 128m

  netflix-eureka:
    build: netflix-eureka
    image: netflix-eureka:1.0.0
    container_name: netflix-eureka
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 8s
      retries: 5
    ports:
      - "8761:8761"
    depends_on:
      configuration-server:
        condition: service_healthy
    environment:
      CONFIGURATION_SERVER_URI: http://configuration-server:8080/
    restart: on-failure:5
    networks:
      - ridesharex-net
    mem_limit: 128m

  api-gateway:
    build: api-gateway
    image: api-gateway:1.0.0
    container_name: api-gateway
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 8s
      retries: 5
    ports:
      - "8080:8080"
    depends_on:
      configuration-server:
        condition: service_healthy
      netflix-eureka:
        condition: service_healthy
    environment:
      CONFIGURATION_SERVER_URI: http://configuration-server:8080/
      EUREKA_URI: http://netflix-eureka:8761/eureka
      DB_AUTH_USERNAME: ${DB_AUTH_USERNAME}
      DB_AUTH_PASSWORD: ${DB_AUTH_PASSWORD}
      JWS_SECRET_KEY: ${JWS_SECRET_KEY}
      SQL_URI: jdbc:postgresql://postgres-auth:5432/auth_db
    restart: on-failure:5
    networks:
      - ridesharex-net
    mem_limit: 128m

  auth:
    build: auth
    image: auth:1.0.0
    container_name: auth
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 8s
      retries: 5
    ports:
      - "8081:8080"
    depends_on:
      postgres-auth:
        condition: service_healthy
      configuration-server:
        condition: service_healthy
      netflix-eureka:
        condition: service_healthy
      api-gateway:
        condition: service_healthy
    environment:
      CONFIGURATION_SERVER_URI: http://configuration-server:8080/
      EUREKA_URI: http://netflix-eureka:8761/eureka
      DB_AUTH_USERNAME: ${DB_AUTH_USERNAME}
      DB_AUTH_PASSWORD: ${DB_AUTH_PASSWORD}
      SQL_URI: jdbc:postgresql://postgres-auth:5432/auth_db
      JWE_SECRET_KEY: ${JWE_SECRET_KEY}
      JWS_SECRET_KEY: ${JWS_SECRET_KEY}
    restart: on-failure:5
    networks:
      - ridesharex-net
    mem_limit: 128m

networks:
  ridesharex-net:
    driver: bridge