services:
  configuration-server:
    build: config-server
    image: config-server:1.0.0
    container_name: config-server
    ports:
      - "8888:8080"
    environment:
      GIT_USER: ${GIT_USER}
      CONFIG_REPOSITORY: ${CONFIG_REPOSITORY}
      GIT_PASSWORD: ${GIT_PASSWORD}
    restart: on-failure:5
    networks:
      - ridesharex-net
    mem_limit: 128m
networks:
  ridesharex-net:
    driver: bridge