services:

  postgres-ride:
    image: postgres:latest
    container_name: postgres-ride
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME_RIDE_MICROSERVICE} -d ride_db" ]
      interval: 10s
      timeout: 8s
      retries: 5
    environment:
      POSTGRES_USER: ${DB_USERNAME_RIDE_MICROSERVICE}
      POSTGRES_PASSWORD: ${DB_PASSWORD_RIDE_MICROSERVICE}
      POSTGRES_DB: ride_db
      PGDATA: /data/postgres
    ports:
      - '5431:5432'
    volumes:
      - C:\postgres-container-data\ride:/data/postgres
    networks:
      - ridesharex-net
    restart: unless-stopped

  configuration-server:
    build: config-server
    image: config-server:1.0.0
    container_name: config-server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 8s
      retries: 5
    ports:
      - "8888:8080"
    environment:
      GIT_USER: ${GIT_USER}
      CONFIG_REPOSITORY: ${CONFIG_REPOSITORY}
      GIT_PASSWORD: ${GIT_PASSWORD}
    restart: on-failure:5
    networks:
      - ridesharex-net
    mem_limit: 128m

  netflix-eureka:
    build: netflix-eureka
    image: netflix-eureka:1.0.0
    container_name: netflix-eureka
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 8s
      retries: 5
    ports:
      - "8761:8761"
    depends_on:
      configuration-server:
        condition: service_healthy
    environment:
      CONFIGURATION_SERVER_URI: http://configuration-server:8080/
    restart: on-failure:5
    networks:
      - ridesharex-net
    mem_limit: 128m

  ride:
    build: ride
    image: ride:1.0.0
    container_name: ride
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 8s
      retries: 5
    ports:
      - "8885:8080"
    depends_on:
      configuration-server:
        condition: service_healthy
      netflix-eureka:
        condition: service_healthy
      postgres-ride:
        condition: service_healthy
    environment:
      CONFIGURATION_SERVER_URI: http://configuration-server:8080/
      EUREKA_URI: http://netflix-eureka:8761/eureka
      DB_USERNAME_RIDE_MICROSERVICE: ${DB_USERNAME_RIDE_MICROSERVICE}
      DB_PASSWORD_RIDE_MICROSERVICE: ${DB_PASSWORD_RIDE_MICROSERVICE}
      SQL_URI: jdbc:postgresql://postgres-ride:5432/ride_db
    restart: on-failure:5
    networks:
      - ridesharex-net
    mem_limit: 256m

networks:
  ridesharex-net:
    driver: bridge