services:

  configuration-server:
    build: config-server
    image: config-server:1.0.0
    container_name: config-server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 8s
      retries: 5
    ports:
      - "8888:8080"
    environment:
      GIT_USER: ${GIT_USER}
      CONFIG_REPOSITORY: ${CONFIG_REPOSITORY}
      GIT_PASSWORD: ${GIT_PASSWORD}
    restart: on-failure:5
    networks:
      - ridesharex-net
    mem_limit: 128m

  netflix-eureka:
    build: netflix-eureka
    image: netflix-eureka:1.0.0
    container_name: netflix-eureka
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 8s
      retries: 5
    ports:
      - "8761:8761"
    depends_on:
      configuration-server:
        condition: service_healthy
    environment:
      CONFIGURATION_SERVER_URI: http://configuration-server:8080/
    restart: on-failure:5
    networks:
      - ridesharex-net
    mem_limit: 128m

  user:
    build: user
    image: user:1.0.0
    container_name: user
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 8s
      retries: 5
    ports:
      - "8886:8080"
    depends_on:
      configuration-server:
        condition: service_healthy
      netflix-eureka:
        condition: service_healthy
    environment:
      CONFIGURATION_SERVER_URI: http://configuration-server:8080/
      EUREKA_URI: http://netflix-eureka:8761/eureka
    restart: on-failure:5
    networks:
      - ridesharex-net
    mem_limit: 256m

networks:
  ridesharex-net:
    driver: bridge