--changeset ublok:1
INSERT INTO country (code, name) VALUES
('PL', 'Poland'),
('DE', 'Germany'),
('FR', 'France'),
('IT', 'Italy'),
('PT', 'Portugal'),
('GB', 'United Kingdom'),
('ES', 'Spain'),
('NL', 'Netherlands'),
('BE', 'Belgium'),
('AT', 'Austria'),
('CH', 'Switzerland'),
('CZ', 'Czech Republic'),
('SK', 'Slovakia'),
('DK', 'Denmark');

--changeset ublok:2
INSERT INTO city (code, name, country) VALUES
-- Poland
('WAW', 'Warsaw', 'PL'),
('KRK', 'Krakow', 'PL'),
('POZ', 'Poznan', 'PL'),
('WRO', 'Wroclaw', 'PL'),
('GDN', 'Gdansk', 'PL'),
('SZC', 'Szczecin', 'PL'),
('BYD', 'Bydgoszcz', 'PL'),
('LUB', 'Lublin', 'PL'),
('KAT', 'Katowice', 'PL'),
('GDY', 'Gdynia', 'PL'),
('CZE', 'Czestochowa', 'PL'),
('RZE', 'Rzeszow', 'PL'),
('SOS', 'Sosnowiec', 'PL'),
('TOR', 'Torun', 'PL'),
('BIA', 'Bialystok', 'PL'),

-- Germany
('BER', 'Berlin', 'DE'),
('MUC', 'Munich', 'DE'),
('FRA', 'Frankfurt', 'DE'),
('HAM', 'Hamburg', 'DE'),
('CGN', 'Cologne', 'DE'),
('STU', 'Stuttgart', 'DE'),
('DUS', 'Dusseldorf', 'DE'),
('DRE', 'Dresden', 'DE'),
('HAN', 'Hanover', 'DE'),
('NUE', 'Nuremberg', 'DE'),
('LEJ', 'Leipzig', 'DE'),
('BRE', 'Bremen', 'DE'),
('ESS', 'Essen', 'DE'),
('DOR', 'Dortmund', 'DE'),
('BIE', 'Bielefeld', 'DE'),

-- France
('PAR', 'Paris', 'FR'),
('LYS', 'Lyon', 'FR'),
('MRS', 'Marseille', 'FR'),
('TLS', 'Toulouse', 'FR'),
('NCE', 'Nice', 'FR'),
('NTE', 'Nantes', 'FR'),
('STR', 'Strasbourg', 'FR'),
('MPL', 'Montpellier', 'FR'),
('BDX', 'Bordeaux', 'FR'),
('LIL', 'Lille', 'FR'),
('REN', 'Rennes', 'FR'),
('REI', 'Reims', 'FR'),
('TCE', 'Toulon', 'FR'),
('GRE', 'Grenoble', 'FR'),
('DIJ', 'Dijon', 'FR'),

-- Italy
('ROM', 'Rome', 'IT'),
('MIL', 'Milan', 'IT'),
('NAP', 'Naples', 'IT'),
('TOR', 'Turin', 'IT'),
('PAL', 'Palermo', 'IT'),
('GEN', 'Genoa', 'IT'),
('BOL', 'Bologna', 'IT'),
('FLR', 'Florence', 'IT'),
('BAR', 'Bari', 'IT'),
('CAT', 'Catania', 'IT'),
('VEN', 'Venice', 'IT'),
('VER', 'Verona', 'IT'),
('MES', 'Messina', 'IT'),
('PAD', 'Padua', 'IT'),
('TRI', 'Trieste', 'IT'),

-- Portugal
('LIS', 'Lisbon', 'PT'),
('POR', 'Porto', 'PT'),
('BRG', 'Braga', 'PT'),
('COI', 'Coimbra', 'PT'),
('FAR', 'Faro', 'PT'),
('AVE', 'Aveiro', 'PT'),
('SET', 'Setubal', 'PT'),
('LEI', 'Leiria', 'PT'),
('VIL', 'Vila Nova de Gaia', 'PT'),
('MAD', 'Madalena', 'PT'),
('LAG', 'Lagos', 'PT'),
('CAS', 'Cascais', 'PT'),
('SIN', 'Sintra', 'PT'),
('FUN', 'Funchal', 'PT'),
('PON', 'Ponta Delgada', 'PT'),

-- United Kingdom
('LON', 'London', 'GB'),
('MAN', 'Manchester', 'GB'),
('BIR', 'Birmingham', 'GB'),
('GLA', 'Glasgow', 'GB'),
('LIV', 'Liverpool', 'GB'),
('BRS', 'Bristol', 'GB'),
('NEW', 'Newcastle', 'GB'),
('LEE', 'Leeds', 'GB'),
('SHE', 'Sheffield', 'GB'),
('EDI', 'Edinburgh', 'GB'),
('NOT', 'Nottingham', 'GB'),
('LEI', 'Leicester', 'GB'),
('CAR', 'Cardiff', 'GB'),
('COV', 'Coventry', 'GB'),
('KIN', 'Kingston upon Hull', 'GB'),

-- Spain
('MAD', 'Madrid', 'ES'),
('BCN', 'Barcelona', 'ES'),
('VAL', 'Valencia', 'ES'),
('SEV', 'Seville', 'ES'),
('ZAZ', 'Zaragoza', 'ES'),
('MAL', 'Malaga', 'ES'),
('MUR', 'Murcia', 'ES'),
('PAL', 'Palma', 'ES'),
('LPD', 'Las Palmas', 'ES'),
('BIL', 'Bilbao', 'ES'),
('ALC', 'Alicante', 'ES'),
('COR', 'Cordoba', 'ES'),
('VLC', 'Valladolid', 'ES'),
('VIT', 'Vitoria-Gasteiz', 'ES'),
('OCO', 'Oviedo', 'ES'),

-- Netherlands
('AMS', 'Amsterdam', 'NL'),
('ROT', 'Rotterdam', 'NL'),
('HAG', 'The Hague', 'NL'),
('UTR', 'Utrecht', 'NL'),
('EIN', 'Eindhoven', 'NL'),
('TIL', 'Tilburg', 'NL'),
('GRO', 'Groningen', 'NL'),
('BRE', 'Breda', 'NL'),
('NIM', 'Nijmegen', 'NL'),
('ENV', 'Enschede', 'NL'),
('APL', 'Apeldoorn', 'NL'),
('HRT', 'Haarlem', 'NL'),
('ARN', 'Arnhem', 'NL'),
('ZWO', 'Zwolle', 'NL'),
('MAA', 'Maastricht', 'NL'),

-- Belgium
('BRU', 'Brussels', 'BE'),
('ANT', 'Antwerp', 'BE'),
('GNT', 'Ghent', 'BE'),
('CHA', 'Charleroi', 'BE'),
('LIE', 'Liege', 'BE'),
('BRG', 'Bruges', 'BE'),
('NAM', 'Namur', 'BE'),
('LUV', 'Leuven', 'BE'),
('MON', 'Mons', 'BE'),
('AAL', 'Aalst', 'BE'),
('MEA', 'Mechelen', 'BE'),
('ROE', 'Roeselare', 'BE'),
('HAS', 'Hasselt', 'BE'),
('KOR', 'Kortrijk', 'BE'),
('TER', 'Tournai', 'BE'),

-- Austria
('VIE', 'Vienna', 'AT'),
('GRZ', 'Graz', 'AT'),
('LIN', 'Linz', 'AT'),
('SAL', 'Salzburg', 'AT'),
('INS', 'Innsbruck', 'AT'),
('KLA', 'Klagenfurt', 'AT'),
('VIL', 'Villach', 'AT'),
('WEL', 'Wels', 'AT'),
('STE', 'St. Pölten', 'AT'),
('DOR', 'Dornbirn', 'AT'),
('WRN', 'Wr. Neustadt', 'AT'),
('FEL', 'Feldkirch', 'AT'),
('BLU', 'Bruck an der Leitha', 'AT'),
('MOD', 'Modling', 'AT'),
('BAU', 'Baden', 'AT'),

-- Switzerland
('ZRH', 'Zurich', 'CH'),
('GEN', 'Geneva', 'CH'),
('BSL', 'Basel', 'CH'),
('LUG', 'Lugano', 'CH'),
('LUC', 'Lucerne', 'CH'),
('STG', 'St. Gallen', 'CH'),
('WIN', 'Winterthur', 'CH'),
('LAU', 'Lausanne', 'CH'),
('THU', 'Thun', 'CH'),
('BIE', 'Biel/Bienne', 'CH'),
('KRI', 'Kriens', 'CH'),
('SIO', 'Sion', 'CH'),
('CHI', 'Chiasso', 'CH'),
('SCZ', 'Schaffhausen', 'CH'),
('FRA', 'Fribourg', 'CH'),

-- Czech Republic
('PRG', 'Prague', 'CZ'),
('BRN', 'Brno', 'CZ'),
('OST', 'Ostrava', 'CZ'),
('PLZ', 'Plzen', 'CZ'),
('LIB', 'Liberec', 'CZ'),
('OLM', 'Olomouc', 'CZ'),
('CBO', 'Ceske Budejovice', 'CZ'),
('HRA', 'Hradec Kralove', 'CZ'),
('ULM', 'Usti nad Labem', 'CZ'),
('PAR', 'Pardubice', 'CZ'),
('ZLN', 'Zlin', 'CZ'),
('KLA', 'Kladno', 'CZ'),
('MOS', 'Most', 'CZ'),
('OPV', 'Opava', 'CZ'),
('FMI', 'Frydek-Mistek', 'CZ'),

-- Slovakia
('BTS', 'Bratislava', 'SK'),
('KOS', 'Kosice', 'SK'),
('PPI', 'Presov', 'SK'),
('ZIL', 'Zilina', 'SK'),
('NIT', 'Nitra', 'SK'),
('TRN', 'Trnava', 'SK'),
('TRE', 'Trencin', 'SK'),
('MRT', 'Martin', 'SK'),
('POP', 'Poprad', 'SK'),
('LUC', 'Lucenec', 'SK'),
('LEV', 'Levice', 'SK'),
('KOM', 'Komarno', 'SK'),
('SPI', 'Spisska Nova Ves', 'SK'),
('HUM', 'Humenne', 'SK'),
('MOL', 'Moldava nad Bodvou', 'SK'),

-- Denmark
('CPH', 'Copenhagen', 'DK'),
('AAR', 'Aarhus', 'DK'),
('ODN', 'Odense', 'DK'),
('AAL', 'Aalborg', 'DK'),
('ESB', 'Esbjerg', 'DK'),
('RAN', 'Randers', 'DK'),
('KOL', 'Kolding', 'DK'),
('HRS', 'Horsens', 'DK'),
('VIB', 'Viborg', 'DK'),
('ROS', 'Roskilde', 'DK'),
('HIL', 'Hillerod', 'DK'),
('SLG', 'Slagelse', 'DK'),
('FRE', 'Frederikshavn', 'DK'),
('HBG', 'Hobro', 'DK')